services:
  mysql:
    image: 'mysql:8.4.7'
    environment:
      - 'MYSQL_DATABASE=testdb'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'